version: '3.8'

services:
  db:
    build: ./db
    container_name: tienda_db
    restart: always
    environment:
      POSTGRES_DB: tienda_perritos
      POSTGRES_USER: usuario_perritos
      POSTGRES_PASSWORD: tiendaperritos123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: tienda_backend
    restart: always
    ports:
      - "3001:3001" # Asumiendo que tu server.js escucha en el puerto 3001
    environment:
      DATABASE_HOST: db
      DATABASE_USER: usuario_perritos
      DATABASE_PASSWORD: tiendaperritos123
      DATABASE_NAME: tienda_perritos
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tienda_frontend
    restart: always
    ports:
      - "80:80" # Tu servidor Nginx (default.conf) expondrá la web en el puerto 80
    depends_on:
      - backend

volumes:
  postgres_data: